#![allow(clippy::exhaustive_enums, reason = "Generated by sol! macro")]
#![allow(clippy::exhaustive_structs, reason = "Generated by sol! macro")]

use alloy::primitives::U256;
use alloy::sol;
use alloy::sol_types::SolCall;
use anyhow::{Context, Result};
use clap::{Args, Subcommand};
use polymarket_client_sdk_v2::types::Address;

use crate::auth;
use crate::output::OutputFormat;
use crate::output::approve::{ApprovalStatus, print_approval_status, print_tx_result};

use super::{
    COLLATERAL_SYMBOL, CONDITIONAL_TOKENS, CTF_COLLATERAL_ADAPTER, CTF_EXCHANGE, NEG_RISK_ADAPTER,
    NEG_RISK_CTF_COLLATERAL_ADAPTER, NEG_RISK_CTF_EXCHANGE, proxy,
};

sol! {
    #[sol(rpc)]
    interface IERC20 {
        function approve(address spender, uint256 value) external returns (bool);
        function allowance(address owner, address spender) external view returns (uint256);
    }

    #[sol(rpc)]
    interface IERC1155 {
        function setApprovalForAll(address operator, bool approved) external;
        function isApprovedForAll(address account, address operator) external view returns (bool);
    }
}

#[derive(Args)]
pub struct ApproveArgs {
    #[command(subcommand)]
    pub command: ApproveCommand,
}

#[derive(Subcommand)]
pub enum ApproveCommand {
    /// Check current contract approvals for a wallet
    Check {
        /// Wallet address to check (defaults to configured wallet)
        address: Option<Address>,
    },
    /// Approve all required contracts for trading (sends on-chain transactions)
    Set,
}

struct ApprovalTarget {
    name: &'static str,
    address: Address,
    needs_collateral_allowance: bool,
    needs_ctf_operator: bool,
}

fn approval_targets() -> Result<Vec<ApprovalTarget>> {
    Ok(vec![
        ApprovalTarget {
            name: "CTF Exchange",
            address: CTF_EXCHANGE,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Neg Risk Exchange",
            address: NEG_RISK_CTF_EXCHANGE,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Neg Risk Adapter",
            address: NEG_RISK_ADAPTER,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Conditional Tokens",
            address: CONDITIONAL_TOKENS,
            needs_collateral_allowance: true,
            needs_ctf_operator: false,
        },
        ApprovalTarget {
            name: "CTF Collateral Adapter",
            address: CTF_COLLATERAL_ADAPTER,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Neg Risk CTF Collateral Adapter",
            address: NEG_RISK_CTF_COLLATERAL_ADAPTER,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
    ])
}

pub async fn execute(
    args: ApproveArgs,
    output: OutputFormat,
    private_key: Option<&str>,
    signature_type: Option<&str>,
) -> Result<()> {
    match args.command {
        ApproveCommand::Check { address } => {
            check(address, private_key, signature_type, output).await
        }
        ApproveCommand::Set => set(private_key, signature_type, output).await,
    }
}

async fn check(
    address_arg: Option<Address>,
    private_key: Option<&str>,
    signature_type: Option<&str>,
    output: OutputFormat,
) -> Result<()> {
    let owner: Address = if let Some(addr) = address_arg {
        addr
    } else if proxy::is_proxy_mode(signature_type)? {
        proxy::derive_proxy_address(private_key)?
    } else {
        let signer = auth::resolve_signer(private_key)?;
        polymarket_client_sdk_v2::auth::Signer::address(&signer)
    };

    let provider = auth::create_readonly_provider().await?;
    let collateral = IERC20::new(super::COLLATERAL_ADDRESS, provider.clone());
    let ctf = IERC1155::new(CONDITIONAL_TOKENS, provider.clone());

    let targets = approval_targets()?;
    let mut statuses = Vec::new();

    for target in &targets {
        let (collateral_allowance, collateral_error) = if target.needs_collateral_allowance {
            match collateral.allowance(owner, target.address).call().await {
                Ok(val) => (val, None),
                Err(e) => (U256::ZERO, Some(e.to_string())),
            }
        } else {
            (U256::ZERO, None)
        };

        let (ctf_approved, ctf_error) = if target.needs_ctf_operator {
            match ctf.isApprovedForAll(owner, target.address).call().await {
                Ok(val) => (Some(val), None),
                Err(e) => (Some(false), Some(e.to_string())),
            }
        } else {
            (None, None)
        };

        statuses.push(ApprovalStatus {
            contract_name: target.name.to_string(),
            contract_address: format!("{}", target.address),
            collateral_allowance,
            ctf_approved,
            collateral_error,
            ctf_error,
        });
    }

    print_approval_status(&statuses, &output)
}

async fn set(
    private_key: Option<&str>,
    signature_type: Option<&str>,
    output: OutputFormat,
) -> Result<()> {
    let use_proxy = proxy::is_proxy_mode(signature_type)?;
    let targets = approval_targets()?;
    let total = targets
        .iter()
        .map(|target| {
            usize::from(target.needs_collateral_allowance) + usize::from(target.needs_ctf_operator)
        })
        .sum();

    if matches!(output, OutputFormat::Table) {
        println!("Approving contracts...\n");
    }

    let mut results: Vec<serde_json::Value> = Vec::new();
    let mut step = 0;

    for target in &targets {
        if target.needs_collateral_allowance {
            step += 1;
            let label = format!("{COLLATERAL_SYMBOL} \u{2192} {}", target.name);
            let calldata = IERC20::approveCall {
                spender: target.address,
                value: U256::MAX,
            }
            .abi_encode();
            let (tx_hash, _) =
                proxy::send_call(private_key, use_proxy, super::COLLATERAL_ADDRESS, calldata)
                    .await
                    .context(format!(
                        "Failed {COLLATERAL_SYMBOL} approval for {}",
                        target.name
                    ))?;

            match output {
                OutputFormat::Table => print_tx_result(step, total, &label, tx_hash),
                OutputFormat::Json => results.push(serde_json::json!({
                    "step": step,
                    "type": "erc20",
                    "asset": COLLATERAL_SYMBOL,
                    "contract": target.name,
                    "tx_hash": format!("{tx_hash}"),
                })),
            }
        }

        if target.needs_ctf_operator {
            step += 1;
            let label = format!("CTF  \u{2192} {}", target.name);
            let calldata = IERC1155::setApprovalForAllCall {
                operator: target.address,
                approved: true,
            }
            .abi_encode();
            let (tx_hash, _) =
                proxy::send_call(private_key, use_proxy, CONDITIONAL_TOKENS, calldata)
                    .await
                    .context(format!("Failed CTF approval for {}", target.name))?;

            match output {
                OutputFormat::Table => print_tx_result(step, total, &label, tx_hash),
                OutputFormat::Json => results.push(serde_json::json!({
                    "step": step,
                    "type": "erc1155",
                    "contract": target.name,
                    "tx_hash": format!("{tx_hash}"),
                })),
            }
        }
    }

    match output {
        OutputFormat::Table => {
            println!("\nAll contracts approved. You're ready to trade.");
        }
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&results)?);
        }
    }

    Ok(())
}

/// TUI-friendly approval check — returns a one-line summary of approvals.
pub(crate) async fn tui_check_approvals() -> Result<String> {
    let owner: Address = if proxy::is_proxy_mode(None)? {
        proxy::derive_proxy_address(None)?
    } else {
        let signer = auth::resolve_signer(None)?;
        polymarket_client_sdk_v2::auth::Signer::address(&signer)
    };

    let provider = auth::create_readonly_provider().await?;
    let collateral = IERC20::new(super::COLLATERAL_ADDRESS, provider.clone());
    let ctf = IERC1155::new(CONDITIONAL_TOKENS, provider.clone());

    let targets = approval_targets()?;
    let mut approved_count = 0;
    let mut total = 0;

    for target in &targets {
        if target.needs_collateral_allowance {
            total += 1;
            if let Ok(val) = collateral.allowance(owner, target.address).call().await {
                if val > U256::ZERO {
                    approved_count += 1;
                }
            }
        }
        if target.needs_ctf_operator {
            total += 1;
            if let Ok(val) = ctf.isApprovedForAll(owner, target.address).call().await {
                if val {
                    approved_count += 1;
                }
            }
        }
    }

    Ok(format!("Approvals: {approved_count}/{total} contracts approved for {owner}"))
}

/// TUI-friendly approval set — runs all approvals, returns a one-line summary.
pub(crate) async fn tui_set_approvals() -> Result<String> {
    let use_proxy = proxy::is_proxy_mode(None)?;
    let targets = approval_targets()?;
    let mut tx_count = 0usize;

    for target in &targets {
        if target.needs_collateral_allowance {
            let calldata = IERC20::approveCall {
                spender: target.address,
                value: U256::MAX,
            }
            .abi_encode();
            proxy::send_call(None, use_proxy, super::COLLATERAL_ADDRESS, calldata)
                .await
                .context(format!("Failed pUSD approval for {}", target.name))?;
            tx_count += 1;
        }

        if target.needs_ctf_operator {
            let calldata = IERC1155::setApprovalForAllCall {
                operator: target.address,
                approved: true,
            }
            .abi_encode();
            proxy::send_call(None, use_proxy, CONDITIONAL_TOKENS, calldata)
                .await
                .context(format!("Failed CTF approval for {}", target.name))?;
            tx_count += 1;
        }
    }

    Ok(format!("✓ {tx_count} approval txns sent — all contracts approved."))
}
